# Generated by Django 5.2.8 on 2025-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purches", "0002_remove_receipt_validated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="file",
        ),
        migrations.AddField(
            model_name="receipt",
            name="file_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
