# Generated by Django 5.2.8 on 2025-11-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purches", "0003_remove_receipt_file_receipt_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="current_approval_level",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="required_approval_levels",
            field=models.IntegerField(default=2),
        ),
    ]
